/**
 * Error codes matching the frozen OpenAPI contract exactly.
 * Do not modify this enum without updating the OpenAPI contract.
 */
export enum ErrorCode {
  // Standard errors
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  RATE_LIMITED = 'RATE_LIMITED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',

  // 409 Conflict errors
  INVALID_STATE_TRANSITION = 'INVALID_STATE_TRANSITION',
  VERSION_CONFLICT = 'VERSION_CONFLICT',
  DUPLICATE_RESOURCE = 'DUPLICATE_RESOURCE',
  IDEMPOTENCY_CONFLICT = 'IDEMPOTENCY_CONFLICT',
  RESOURCE_IN_USE = 'RESOURCE_IN_USE',
  CUSTOMER_APPROVAL_REQUIRED = 'CUSTOMER_APPROVAL_REQUIRED',
  JOB_STAGE_NOT_ALLOWED = 'JOB_STAGE_NOT_ALLOWED',
  JOB_ASSIGNMENT_REQUIRED = 'JOB_ASSIGNMENT_REQUIRED',
  CHECKLIST_INCOMPLETE = 'CHECKLIST_INCOMPLETE',
  QUALITY_CHECK_REQUIRED = 'QUALITY_CHECK_REQUIRED',
  INVOICE_REQUIRED = 'INVOICE_REQUIRED',
  INSUFFICIENT_STOCK = 'INSUFFICIENT_STOCK',
  REVERSAL_EXCEEDS_ISSUED = 'REVERSAL_EXCEEDS_ISSUED',
  RESERVATION_INVALID = 'RESERVATION_INVALID',
  SCHEDULE_CONFLICT = 'SCHEDULE_CONFLICT',
  CONFLICT_NOT_OVERRIDABLE = 'CONFLICT_NOT_OVERRIDABLE',
  SEPARATION_OF_DUTIES_VIOLATION = 'SEPARATION_OF_DUTIES_VIOLATION',
  DUPLICATE_APPROVAL = 'DUPLICATE_APPROVAL',
  RECEIPT_EXCEEDS_ORDERED = 'RECEIPT_EXCEEDS_ORDERED',
  PAYMENT_AMOUNT_MISMATCH = 'PAYMENT_AMOUNT_MISMATCH',
  ASSESSMENT_LOCKED = 'ASSESSMENT_LOCKED',
  CERTIFICATE_NOT_ELIGIBLE = 'CERTIFICATE_NOT_ELIGIBLE',
  ATTACHMENT_INVALID = 'ATTACHMENT_INVALID',
  ATTACHMENT_NOT_LINKABLE = 'ATTACHMENT_NOT_LINKABLE',
  PAYLOAD_TOO_LARGE = 'PAYLOAD_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE = 'UNSUPPORTED_MEDIA_TYPE',
  EXPORT_NOT_READY = 'EXPORT_NOT_READY',
  EXPORT_EXPIRED = 'EXPORT_EXPIRED',
}