// Thin, named re-exports over the generated OpenAPI contract types.
// Application code should import schema types from here (not directly from
// `./generated/schema`) so the generated file remains a pure, disposable
// build artifact.
import type { components } from './generated/schema'
export type { operations as ApiOperations } from './generated/schema'

export type Schemas = components['schemas']

export type LoginRequest = Schemas['LoginRequest']
export type RefreshRequest = Schemas['RefreshRequest']
export type LogoutRequest = Schemas['LogoutRequest']
export type ChangePasswordRequest = Schemas['ChangePasswordRequest']
export type TokenPair = Schemas['TokenPair']
export type CurrentUser = Schemas['CurrentUser']
export type RoleCode = Schemas['RoleCode']
export type Permission = Schemas['Permission']
export type Role = Schemas['Role']
export type RoleList = Schemas['RoleList']
export type ApiErrorBody = Schemas['Error']
export type ErrorCode = Schemas['ErrorCode']
export type ErrorDetail = Schemas['ErrorDetail']
export type Locale = Schemas['Locale']

export type DownloadAuthorization = Schemas['DownloadAuthorization']
export type Uuid = Schemas['Uuid']
export type Timestamp = Schemas['Timestamp']
export type DateOnly = Schemas['DateOnly']
export type PageInfo = Schemas['PageInfo']
export type UserRef = Schemas['UserRef']
export type UserRefPage = Schemas['UserRefPage']

export type User = Schemas['User']
export type UserCreateRequest = Schemas['UserCreateRequest']
export type UserUpdateRequest = Schemas['UserUpdateRequest']
export type RoleAssignmentRequest = Schemas['RoleAssignmentRequest']
export type ScopeAssignmentRequest = Schemas['ScopeAssignmentRequest']
export type UserPage = Schemas['UserPage']

export type OrganizationScope = Schemas['OrganizationScope']
export type OrganizationScopeCreateRequest = Schemas['OrganizationScopeCreateRequest']
export type OrganizationScopeUpdateRequest = Schemas['OrganizationScopeUpdateRequest']
export type OrganizationScopePage = Schemas['OrganizationScopePage']

export type ContactPreferences = Schemas['ContactPreferences']
export type Customer = Schemas['Customer']
export type CustomerCreateRequest = Schemas['CustomerCreateRequest']
export type CustomerUpdateRequest = Schemas['CustomerUpdateRequest']
export type CustomerPage = Schemas['CustomerPage']

export type NextService = Schemas['NextService']
export type ServiceHistoryItem = Schemas['ServiceHistoryItem']
export type ServiceHistoryPage = Schemas['ServiceHistoryPage']
export type Vehicle = Schemas['Vehicle']
export type VehicleCreateRequest = Schemas['VehicleCreateRequest']
export type VehicleUpdateRequest = Schemas['VehicleUpdateRequest']
export type VehiclePage = Schemas['VehiclePage']

export type ServiceReminder = Schemas['ServiceReminder']
/**
 * The generated `ServiceReminderCreateRequest` collapses to a `{title, dueDate?,
 * dueMileage?, notes?} | unknown | unknown` union due to an openapi-typescript
 * oneOf artifact on the contract's "at least one of dueDate/dueMileage
 * required" constraint. The object shape is the only one ever constructed by
 * this app; the constraint itself is enforced client-side and by the backend.
 */
export type ServiceReminderCreateRequest = {
  title: string
  dueDate?: DateOnly
  dueMileage?: number
  notes?: string
}
export type ServiceReminderUpdateRequest = Schemas['ServiceReminderUpdateRequest']
export type ServiceReminderPage = Schemas['ServiceReminderPage']

export type Bay = Schemas['Bay']
export type BayCreateRequest = Schemas['BayCreateRequest']
export type BayUpdateRequest = Schemas['BayUpdateRequest']
export type BayPage = Schemas['BayPage']
export type CalendarReference = Schemas['CalendarReference']
export type BayCalendar = Schemas['BayCalendar']

// --- Jobs / workshop execution ---
export type JobStage = Schemas['JobStage']
export type JobPriority = Schemas['JobPriority']
export type ServiceType = Schemas['ServiceType']
export type JobApprovalSummary = Schemas['JobApprovalSummary']
export type JobCard = Schemas['JobCard']
export type JobCardCreateRequest = Schemas['JobCardCreateRequest']
export type JobCardUpdateRequest = Schemas['JobCardUpdateRequest']
export type JobCardPage = Schemas['JobCardPage']
export type JobAssignmentRequest = Schemas['JobAssignmentRequest']
export type JobTransitionRequest = Schemas['JobTransitionRequest']
export type JobStageEvent = Schemas['JobStageEvent']
export type JobStageEventPage = Schemas['JobStageEventPage']
export type WorkItem = Schemas['WorkItem']
export type WorkItemCreateRequest = Schemas['WorkItemCreateRequest']
export type WorkItemUpdateRequest = Schemas['WorkItemUpdateRequest']
export type WorkItemPage = Schemas['WorkItemPage']
export type QualityCheck = Schemas['QualityCheck']
export type QualityCheckCreateRequest = Schemas['QualityCheckCreateRequest']
export type QualityCheckPage = Schemas['QualityCheckPage']
export type ApprovalScope = Schemas['ApprovalScope']
export type JobApproval = Schemas['JobApproval']
export type JobApprovalCreateRequest = Schemas['JobApprovalCreateRequest']
export type JobApprovalDecisionRequest = Schemas['JobApprovalDecisionRequest']
export type JobApprovalPage = Schemas['JobApprovalPage']
export type LaborEntry = Schemas['LaborEntry']
export type LaborEntryCreateRequest = Schemas['LaborEntryCreateRequest']
export type LaborEntryUpdateRequest = Schemas['LaborEntryUpdateRequest']
export type LaborEntryPage = Schemas['LaborEntryPage']
export type PartIssue = Schemas['PartIssue']
export type PartIssueCreateRequest = Schemas['PartIssueCreateRequest']
export type PartIssueReversalRequest = Schemas['PartIssueReversalRequest']
export type PartIssueReversal = Schemas['PartIssueReversal']
export type PartIssuePage = Schemas['PartIssuePage']
export type PartReservation = Schemas['PartReservation']
export type PartReservationCreateRequest = Schemas['PartReservationCreateRequest']
export type PartReservationPage = Schemas['PartReservationPage']
export type SubletEntry = Schemas['SubletEntry']
export type SubletEntryCreateRequest = Schemas['SubletEntryCreateRequest']
export type SubletEntryPage = Schemas['SubletEntryPage']
export type Attachment = Schemas['Attachment']
export type AttachmentPage = Schemas['AttachmentPage']
export type JobAttachmentLinkRequest = Schemas['JobAttachmentLinkRequest']
export type InvoiceSummary = Schemas['InvoiceSummary']
export type Invoice = Schemas['Invoice']
export type InvoiceLine = Schemas['InvoiceLine']
export type ReasonRequest = Schemas['ReasonRequest']
export type InvoicePage = Schemas['InvoicePage']
export type InvoiceUpdateRequest = Schemas['InvoiceUpdateRequest']
export type InvoiceTransitionRequest = Schemas['InvoiceTransitionRequest']
export type PaymentReference = Schemas['PaymentReference']
export type PaymentCreateRequest = Schemas['PaymentCreateRequest']
export type CustomerStatement = Schemas['CustomerStatement']
export type StatementLine = Schemas['StatementLine']

// --- Inventory / stock ---
export type Store = Schemas['Store']
export type StoreCreateRequest = Schemas['StoreCreateRequest']
export type StoreUpdateRequest = Schemas['StoreUpdateRequest']
export type StorePage = Schemas['StorePage']
export type VehicleCompatibility = Schemas['VehicleCompatibility']
export type Part = Schemas['Part']
export type PartCreateRequest = Schemas['PartCreateRequest']
export type PartUpdateRequest = Schemas['PartUpdateRequest']
export type PartPage = Schemas['PartPage']
export type StockBalance = Schemas['StockBalance']
export type StockLevelsUpdateRequest = Schemas['StockLevelsUpdateRequest']
export type StockBalancePage = Schemas['StockBalancePage']
export type StockMovementType = Schemas['StockMovementType']
export type StockMovement = Schemas['StockMovement']
export type StockMovementPage = Schemas['StockMovementPage']
export type StockReconciliation = Schemas['StockReconciliation']
export type StockAdjustment = Schemas['StockAdjustment']
export type StockAdjustmentCreateRequest = Schemas['StockAdjustmentCreateRequest']
export type StockAdjustmentDecisionRequest = Schemas['StockAdjustmentDecisionRequest']
export type StockAdjustmentPage = Schemas['StockAdjustmentPage']

// --- Purchasing ---
export type Vendor = Schemas['Vendor']
export type VendorCreateRequest = Schemas['VendorCreateRequest']
export type VendorUpdateRequest = Schemas['VendorUpdateRequest']
export type VendorPage = Schemas['VendorPage']
export type PurchaseOrderStatus = Schemas['PurchaseOrderStatus']
export type PurchaseOrderLine = Schemas['PurchaseOrderLine']
export type PurchaseOrderLineRequest = Schemas['PurchaseOrderLineRequest']
export type PurchaseOrder = Schemas['PurchaseOrder']
export type PurchaseOrderCreateRequest = Schemas['PurchaseOrderCreateRequest']
export type PurchaseOrderUpdateRequest = Schemas['PurchaseOrderUpdateRequest']
export type PurchaseOrderTransitionRequest = Schemas['PurchaseOrderTransitionRequest']
export type PurchaseOrderPage = Schemas['PurchaseOrderPage']
export type PurchaseApproval = Schemas['PurchaseApproval']
export type PurchaseApprovalRequest = Schemas['PurchaseApprovalRequest']
export type PurchaseApprovalPage = Schemas['PurchaseApprovalPage']
export type GoodsReceiptLine = Schemas['GoodsReceiptLine']
export type GoodsReceiptLineRequest = Schemas['GoodsReceiptLineRequest']
export type GoodsReceipt = Schemas['GoodsReceipt']
export type GoodsReceiptCreateRequest = Schemas['GoodsReceiptCreateRequest']
export type GoodsReceiptPage = Schemas['GoodsReceiptPage']
export type Money = Schemas['Money']
export type FinanceSettings = Schemas['FinanceSettings']
export type FinanceSettingsUpdateRequest = Schemas['FinanceSettingsUpdateRequest']
export type ApprovalTier = Schemas['ApprovalTier']
export type PurchaseApprovalPolicy = Schemas['PurchaseApprovalPolicy']
export type PurchaseApprovalPolicyUpdateRequest = Schemas['PurchaseApprovalPolicyUpdateRequest']

// --- Dashboards / exports / audit ---
export type ReportFilters = Schemas['ReportFilters']
export type Metric = Schemas['Metric']
export type DashboardResponse = Schemas['DashboardResponse']
export type ExportType = Schemas['ExportType']
export type ExportStatus = Schemas['ExportStatus']
export type ExportJobCreateRequest = Schemas['ExportJobCreateRequest']
export type ExportJob = Schemas['ExportJob']
export type ExportJobPage = Schemas['ExportJobPage']
export type AuditChange = Schemas['AuditChange']
export type AuditEvent = Schemas['AuditEvent']
export type AuditEventPage = Schemas['AuditEventPage']

// --- Predictions (advisory only; never auto-executed) ---
export type PredictionType = Schemas['PredictionType']
export type PredictionStatus = Schemas['PredictionStatus']
export type PredictionSource = Schemas['PredictionSource']
export type PredictionExplanation = Schemas['PredictionExplanation']
export type ReorderDetail = Schemas['ReorderDetail']
export type TrainingRiskDetail = Schemas['TrainingRiskDetail']
export type Prediction = Schemas['Prediction']
export type PredictionDecisionRequest = Schemas['PredictionDecisionRequest']
export type PredictionRunRequest = Schemas['PredictionRunRequest']
export type PredictionRun = Schemas['PredictionRun']
export type PredictionPage = Schemas['PredictionPage']
export type PredictionSettings = Schemas['PredictionSettings']
export type PredictionSettingsUpdateRequest = Schemas['PredictionSettingsUpdateRequest']
